#!/bin/bash
ROOT_DIR=$(dirname $(dirname $(dirname $(realpath $0))))
UTILS_DIR=$ROOT_DIR/vnetUtils/helper

$UTILS_DIR/vecho "\e[1;34m$0 $*\e[0m"
$UTILS_DIR/vdo iptables -t filter -I FORWARD -j DROP
$UTILS_DIR/vdo iptables -t filter -I INPUT -j DROP
$UTILS_DIR/vdo iptables -t filter -I OUTPUT -j DROP
$UTILS_DIR/vdo arptables -A INPUT -j DROP