#!/bin/bash
ROOT_DIR=$(dirname $(dirname $(dirname $(realpath $0))))
UTILS_DIR=$ROOT_DIR/vnetUtils/helper

$UTILS_DIR/vecho "\e[1;34m$0 $*\e[0m"
$UTILS_DIR/addVethPair $3 $4
$UTILS_DIR/setNS $3 $1
$UTILS_DIR/setNS $4 $2
$UTILS_DIR/execNS $1 $UTILS_DIR/giveAddr $3 $5.1/24
$UTILS_DIR/execNS $2 $UTILS_DIR/giveAddr $4 $5.2/24
$UTILS_DIR/execNS $1 $UTILS_DIR/setRoute $5.0/24 $3
$UTILS_DIR/execNS $2 $UTILS_DIR/setRoute $5.0/24 $4
