#!/bin/bash
ROOT_DIR=$(dirname $(dirname $(dirname $(realpath $0))))
UTILS_DIR=$ROOT_DIR/vnetUtils/helper

$UTILS_DIR/vecho "\e[1;34m$0 $*\e[0m"
if [[ "s${1: -3:3}" = "sns0" ]]; 
then
    $UTILS_DIR/vdo nsenter -t $$ -n -- ${*#$1}
else
    $UTILS_DIR/vdo ip netns exec $*
fi
