#!/bin/bash
ROOT_DIR=$(dirname $(dirname $(dirname $(realpath $0))))
UTILS_DIR=$ROOT_DIR/vnetUtils/helper

$UTILS_DIR/vecho "\e[1;34m$0 $*\e[0m"
$UTILS_DIR/vdo ip route del $1 2> /dev/null
$UTILS_DIR/vdo ip route add $1 dev $2 via $3
